feat: createad CDK Stack to create IAM role for OIDC auth in github workflows

diff --git a/run b/run
--- a/run
+++ b/run
@@ -50,6 +50,28 @@ cdk-deploy () {
     cdk deploy --app 'uv run --script infra.py' '*' --profile $AWS_PROFILE --region $AWS_REGION
 }
 
+cdk-deploy:github_oidc_stack () {
+	set -x
+	local github_repo=${1}	# avr2002/files-api
+	local create_oidc_provider=${2:-false}	# boolean to indicate whether to create a new OIDC provider
+
+	if [ -z "$github_repo" ]; then
+		echo "ERROR: GitHub repository not specified. Usage: cdk-deploy:github_oidc_stack <github_repo>. E.g., avr2002/files-api"
+		exit 1
+	fi
+
+	# Check if create_oidc_provider is a boolean
+	if [[ "$create_oidc_provider" != "true" && "$create_oidc_provider" != "false" ]]; then
+		echo "ERROR: create_oidc_provider must be 'true' or 'false'."
+		exit 1
+	fi
+
+	cdk deploy --app 'uv run --script github_oidc_infra.py' '*' \
+		--context github_repo="$github_repo" \
+		--context create_oidc_provider="$create_oidc_provider" \
+		--profile $AWS_PROFILE --region $AWS_REGION
+}
+
 cdk-destroy () {
     cdk destroy --app 'uv run --script infra.py' '*' --profile $AWS_PROFILE --region $AWS_REGION
 }
